//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STMRegistration
    {
        public Nullable<bool> concessionsForm { get; set; }
        public Nullable<bool> paidFees { get; set; }
        public string howPaid { get; set; }
        public Nullable<int> totalFees { get; set; }
        public Nullable<int> feesOwed { get; set; }
        public string parent1Name { get; set; }
        public string parent1Address { get; set; }
        public string parent1City { get; set; }
        public Nullable<int> parent1Zip { get; set; }
        public string parent1HomePhone { get; set; }
        public string parent1WorkPhone { get; set; }
        public string parent1CellPhone { get; set; }
        public string parent1Employer { get; set; }
        public string parent1Email { get; set; }
        public string parent2Name { get; set; }
        public string parent2Address { get; set; }
        public string parent2City { get; set; }
        public Nullable<int> parent2Zip { get; set; }
        public string parent2HomePhone { get; set; }
        public string parent2WorkPhone { get; set; }
        public string parent2CellPhone { get; set; }
        public string parent2Employer { get; set; }
        public string parent2Email { get; set; }
        public string child1Name { get; set; }
        public string child1Address { get; set; }
        public string child1City { get; set; }
        public Nullable<int> child1Zip { get; set; }
        public string child1Phone { get; set; }
        public string child1Sex { get; set; }
        public Nullable<System.DateTime> child1Birthday { get; set; }
        public string child1Birthplace { get; set; }
        public Nullable<bool> child1Volleyball { get; set; }
        public Nullable<bool> child1Basketball { get; set; }
        public Nullable<bool> child1Track { get; set; }
        public Nullable<int> child1Grade { get; set; }
        public string child1Status { get; set; }
        public Nullable<bool> child1Medical { get; set; }
        public Nullable<bool> child1Concussion { get; set; }
        public Nullable<bool> child1Risk { get; set; }
        public Nullable<bool> child1Physical { get; set; }
        public Nullable<bool> child1SportsmanPlayer { get; set; }
        public Nullable<bool> child1SportsmanParent { get; set; }
        public string child2Name { get; set; }
        public string child2Address { get; set; }
        public string child2City { get; set; }
        public Nullable<int> child2Zip { get; set; }
        public string child2Phone { get; set; }
        public string child2Sex { get; set; }
        public Nullable<System.DateTime> child2Birthday { get; set; }
        public string child2Birthplace { get; set; }
        public Nullable<bool> child2Volleyball { get; set; }
        public Nullable<bool> child2Basketball { get; set; }
        public Nullable<bool> child2Track { get; set; }
        public Nullable<int> child2Grade { get; set; }
        public string child2Status { get; set; }
        public Nullable<bool> child2Medical { get; set; }
        public Nullable<bool> child2Concussion { get; set; }
        public Nullable<bool> child2Risk { get; set; }
        public Nullable<bool> child2Physical { get; set; }
        public Nullable<bool> child2SportsmanPlayer { get; set; }
        public Nullable<bool> child2SportsmanParent { get; set; }
        public string child3Name { get; set; }
        public string child3Address { get; set; }
        public string child3City { get; set; }
        public Nullable<int> child3Zip { get; set; }
        public string child3Phone { get; set; }
        public string child3Sex { get; set; }
        public Nullable<System.DateTime> child3Birthday { get; set; }
        public string child3Birthplace { get; set; }
        public Nullable<bool> child3Volleyball { get; set; }
        public Nullable<bool> child3Basketball { get; set; }
        public Nullable<bool> child3Track { get; set; }
        public Nullable<int> child3Grade { get; set; }
        public string child3Status { get; set; }
        public Nullable<bool> child3Medical { get; set; }
        public Nullable<bool> child3Concussion { get; set; }
        public Nullable<bool> child3Risk { get; set; }
        public Nullable<bool> child3Physical { get; set; }
        public Nullable<bool> child3SportsmanPlayer { get; set; }
        public Nullable<bool> child3SportsmanParent { get; set; }
        public string child4Name { get; set; }
        public string child4Address { get; set; }
        public string child4City { get; set; }
        public Nullable<int> child4Zip { get; set; }
        public string child4Phone { get; set; }
        public string child4Sex { get; set; }
        public Nullable<System.DateTime> child4Birthday { get; set; }
        public string child4Birthplace { get; set; }
        public Nullable<bool> child4Volleyball { get; set; }
        public Nullable<bool> child4Basketball { get; set; }
        public Nullable<bool> child4Track { get; set; }
        public Nullable<int> child4Grade { get; set; }
        public string child4Status { get; set; }
        public Nullable<bool> child4Medical { get; set; }
        public Nullable<bool> child4Concussion { get; set; }
        public Nullable<bool> child4Risk { get; set; }
        public Nullable<bool> child4Physical { get; set; }
        public Nullable<bool> child4SportsmanPlayer { get; set; }
        public Nullable<bool> child4SportsmanParent { get; set; }
        public int Id { get; set; }
    }
}
